# Generated by Django 6.1 on 2026-08-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_rawdocument_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawDocument',
            new_name='Document',
        ),
    ]
