# Generated by Django 6.1 on 2026-08-19 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunks', models.ManyToManyField(related_name='wiki_pages', to='wiki.chunk')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.workspace')),
            ],
        ),
    ]
